"""Hover tooltip text for metric abbreviations (injected as template variable ``G``)."""

GLOSSARY: dict[str, str] = {
    "revenue": "Total sales (usually trailing twelve months, TTM).",
    "net_income": "Profit after all expenses and taxes (TTM).",
    "cfo": "Operating cash flow (CFO): cash from core operations (TTM).",
    "capex": "Capital expenditures: cash spent on PP&E, factories, servers, etc. (TTM).",
    "fcf": "Free cash flow: cash after operations minus capex; uses reported FCF when available (TTM).",
    "gross_margin": "Gross profit ÷ revenue — markup before operating costs.",
    "net_margin": "Net income ÷ revenue — bottom-line profit margin.",
    "roe": "Return on equity — net income as % of shareholder equity.",
    "roic": "Return on invested capital — profit vs debt + equity capital employed.",
    "pe": "Price-to-earnings — share price ÷ earnings per share.",
    "peg": "PEG ratio — P/E divided by expected growth % (lower can mean cheaper vs growth).",
    "ev_ebitda": "Enterprise value ÷ EBITDA — valuation multiple including net debt.",
    "fcf_yield": "Free cash flow per share ÷ stock price — cash return to holders.",
    "de": "Debt-to-equity — total debt relative to shareholder equity.",
    "current_ratio": "Current assets ÷ current liabilities — short-term liquidity.",
    "altman_z": "Altman Z-score — bankruptcy-risk index (higher generally safer).",
    "piotroski": "Piotroski F-score — nine-point financial strength checklist (0–9).",
    "rev_growth_1y": "Revenue growth: latest TTM vs prior-year TTM.",
    "oeps_cagr": "Owner earnings per share CAGR — growth in (OCF − capex − SBC) per share.",
    "ttm": "Trailing twelve months — sum of the last four reported quarters.",
    "eps": "Earnings per share — net income divided by shares.",
    "oeps": "Owner earnings per share — (operating cash flow − capex − stock comp) per share.",
    "ebit": "Earnings before interest and taxes — operating profit.",
    "ebitda": "EBIT plus depreciation & amortization — proxy for operating cash capacity.",
    "quality": "Quality sub-score (0–5): profitability, stability, cash conversion.",
    "value": "Value sub-score (0–5): cheapness vs earnings, cash flow, book.",
    "growth": "Growth sub-score (0–5): revenue and owner-earnings trends.",
    "safety": "Safety sub-score (0–5): balance sheet, leverage, distress signals.",
    "score_20": "Composite investment score from the model (0–20 scale).",
    "screener_rank": "Dashboard sort score: blends Q/V/G/S with scale, sanity checks, and multi-year revenue/OEPS growth.",
    "momentum_score": "Short-term growth score (0–20): TTM and latest-quarter revenue/EPS growth plus revenue acceleration from quarterly filings.",
    "momentum_rank": "Universe rank by short-term growth score — use to pick names for deeper quarterly review.",
    "w52_high": "Highest traded price in the last 52 weeks.",
    "w52_low": "Lowest traded price in the last 52 weeks.",
    "dma50": "50-day moving average — short-term trend price.",
    "dma200": "200-day moving average — long-term trend price.",
    "beta": "Volatility vs the market; 1.0 ≈ moves with the index.",
    "qvgs": "Quality · Value · Growth · Safety — four sub-scores, each 0–5.",
    "rev_1y": "Revenue growth, TTM vs prior-year TTM.",
    "eps_1y": "EPS growth, TTM vs prior-year TTM.",
    "rev_5y": "Revenue compound annual growth over ~4–5 years.",
    "mcap": "Market capitalization — share price × shares outstanding.",
    "analyst": "Street consensus rating (typically 1 = strong sell, 5 = strong buy).",
    "live_quote": "Quote from EODHD by listing exchange: Live / Pre-market / After-hours (US) when fresh; Closed or Last trade when the market is shut or the timestamp is stale.",
    "ttm_bar": "Trailing twelve months — last four quarters summed.",
    "ytd": "Year to date — from Jan 1 through the latest trading day.",
    "dma": "Daily moving average of the closing price.",
}
